parameters:
    project_punchclock.listener.core.class: ProjectPunchclock\Bundle\CoreBundle\Listener\CoreListener
    
    project_punchclock.menu.builder.class: ProjectPunchclock\Bundle\CoreBundle\Menu\MenuBuilder
    project_punchclock.menu.main.class: Knp\Menu\MenuItem
    project_punchclock.menu.nonauth.class: Knp\Menu\MenuItem
    project_punchclock.menu.voter.request.class: ProjectPunchclock\Bundle\CoreBundle\Menu\RequestVoter
    
    project_punchclock.inflector.class: ProjectPunchclock\Bundle\CoreBundle\Inflector\Inflector
    
    project_punchclock.controller.core.class: ProjectPunchclock\Bundle\CoreBundle\Controller\CoreController
  
services:
    project_punchclock.listener.core:
        class: %project_punchclock.listener.core.class%
        tags: [{ name: kernel.event_listener, event: kernel.request, method: onKernelRequest }]
        arguments: [ @service_container ]
    
    project_punchclock.menu.builder:
        class: %project_punchclock.menu.builder.class%
        arguments: ["@knp_menu.factory", "@security.context", "@translator"]
    project_punchclock.menu.main:
        class: %project_punchclock.menu.main.class%
        factory_service: project_punchclock.menu.builder
        factory_method: createMainMenu
        arguments: [ "@request" ]
        scope: request
        tags: [{ name: knp_menu.menu, alias: main }]
    project_punchclock.menu.nonauth:
        class: %project_punchclock.menu.nonauth.class%
        factory_service: project_punchclock.menu.builder
        factory_method: createNonAuthMenu
        arguments: [ "@request" ]
        scope: request
        tags: [{ name: knp_menu.menu, alias: nonauth }]          
    project_punchclock.menu.voter.request:
        class: %project_punchclock.menu.voter.request.class%
        arguments: [ "@service_container" ]
        tags: [{ name: knp_menu.voter }]
            
    project_punchclock.inflector: 
        class: %project_punchclock.inflector.class%
    
    project_punchclock.controller.core:
        class: "%project_punchclock.controller.core.class%"
        arguments: [ "@sylius.controller.configuration_factory" ]
